site_name: Fluxtion stream processing
site_description: High-performance, event-driven server framework
site_url: https://telaminai.github.io/mongoose/
repo_url: https://github.com/telaminai/mongoose
repo_name: telaminai/mongoose
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - attr_list
  - tables

plugins:
  - search
  - mermaid2
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telaminai
  # Define variables here
  source_root: https://github.com/telaminai/mongoose/tree/main/src
  example_root: https://github.com/telaminai/mongoose-examples/tree/main
  fluxtion_src_runtime: https://github.com/telaminai/mongoose-examples/tree/main
  fluxtion_example_src: https://github.com/telaminai/mongoose-examples/tree/main
  mongoose_version: 1.0.6
  release_date: "2024-09-13"

nav:
  - Home:
      - index: index.md
      - fundamentals: home/dataflow-fundamentals.md
  - Reference guide:
      - Quick reference: reference/reference-documentation.md
      - functional streams:
          - DSL introduction: reference/functional/overview-functional.md
          - DataFlow: reference/functional/dataflow-functional-dsl.md
          - DataFlow groupBy: reference/functional/dataflow-functional-groupby-dsl.md
      - Combine functional and imperative: reference/connecting-dsl-imperative.md
